-- Phase 2 Part A — intelligence_items storage for RSS and future sources
-- Run order: after migrations 001–003
--
-- PREREQUISITE: pgvector extension must be enabled in Supabase before running
-- this migration. Enable it via: Supabase Dashboard → Database → Extensions →
-- search "vector" → enable. If pgvector is not available on your plan, the
-- CREATE EXTENSION statement below will fail — that is the expected signal.

-- Enable pgvector (safe to re-run — IF NOT EXISTS is a no-op if already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- ────────────────────────────────────────────────────────────────────────────
-- intelligence_items
-- Canonical store for all ingested content from RSS, LinkedIn, AIS, etc.
-- Rows are deduplicated on url (UNIQUE constraint).
-- embedding column is NULL until the embeddings step runs (Phase 2 Part B Step 3).
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS intelligence_items (
  id           TEXT PRIMARY KEY,                          -- nanoid-generated by ingestion runner
  source_type  TEXT NOT NULL,                             -- 'rss' | 'linkedin' | 'vessel_ais' | ...
  source_name  TEXT NOT NULL,                             -- e.g. 'Splash247', 'gCaptain'
  url          TEXT NOT NULL UNIQUE,                      -- canonical article URL, used for dedup
  title        TEXT NOT NULL,
  snippet      TEXT,                                      -- RSS description / contentSnippet
  raw_text     TEXT,                                      -- full article body (NULL until Jina step runs)
  embedding    vector(1536),                              -- OpenAI text-embedding-3-small (NULL until embeddings step)
  published_at TIMESTAMPTZ,                               -- from RSS pubDate
  ingested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata     JSONB NOT NULL DEFAULT '{}'::jsonb         -- source-specific extras: author, categories, guid
);

CREATE INDEX IF NOT EXISTS idx_intelligence_items_source_type  ON intelligence_items (source_type);
CREATE INDEX IF NOT EXISTS idx_intelligence_items_published_at ON intelligence_items (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_intelligence_items_source_name  ON intelligence_items (source_name);
CREATE INDEX IF NOT EXISTS idx_intelligence_items_ingested_at  ON intelligence_items (ingested_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- ingestion_runs
-- Audit trail for every ingestion run — one row per source per run.
-- Used for monitoring feed health and debugging.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ingestion_runs (
  id             TEXT PRIMARY KEY,
  source_type    TEXT NOT NULL,
  source_name    TEXT NOT NULL,
  started_at     TIMESTAMPTZ NOT NULL,
  completed_at   TIMESTAMPTZ,
  items_found    INTEGER NOT NULL DEFAULT 0,
  items_new      INTEGER NOT NULL DEFAULT 0,
  items_skipped  INTEGER NOT NULL DEFAULT 0,
  error          TEXT
);

CREATE INDEX IF NOT EXISTS idx_ingestion_runs_source_name ON ingestion_runs (source_name);
CREATE INDEX IF NOT EXISTS idx_ingestion_runs_started_at  ON ingestion_runs (started_at DESC);
