-- Migration 011: feedback table
--
-- Stores per-brief subscriber feedback (rating + optional message).
-- id is a nanoid string generated by the API.  briefJobId links back to
-- brief_jobs; subscriber_id identifies who submitted the feedback.
--
-- Run once against your Supabase project (SQL Editor → Run).
--
-- NOTE: If a 'feedback' table already exists from an earlier schema, the
-- CREATE TABLE IF NOT EXISTS will be a no-op and the ALTER TABLE statements
-- below will add the missing columns to the existing table.

CREATE TABLE IF NOT EXISTS feedback (
  id             TEXT        PRIMARY KEY,
  subscriber_id  TEXT        NOT NULL DEFAULT '',
  brief_job_id   TEXT,
  rating         TEXT,        -- 'good' | 'ok' | 'bad'
  message        TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add columns that may be absent when table was created with an older schema.
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS subscriber_id TEXT DEFAULT '';
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS brief_job_id  TEXT;
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS rating        TEXT;

CREATE INDEX IF NOT EXISTS idx_feedback_subscriber ON feedback (subscriber_id);
CREATE INDEX IF NOT EXISTS idx_feedback_created    ON feedback (created_at DESC);
