/**
 * IntelSource — the plugin interface for all intelligence ingestion sources.
 *
 * Every source (RSS, LinkedIn, AIS, etc.) implements IntelSource and registers
 * itself via registerSource(). The ingestion runner iterates registeredSources
 * on a schedule set by each source's scheduleMinutes property.
 */

// ---------------------------------------------------------------------------
// Core types
// ---------------------------------------------------------------------------

export interface IntelItem {
  id: string;                          // nanoid, generated by the source implementation
  source_type: string;                 // e.g. 'rss'
  source_name: string;                 // e.g. 'Splash247'
  url: string;                         // canonical article URL — used for dedup
  title: string;
  snippet: string | null;              // RSS description / contentSnippet / excerpt
  published_at: string | null;         // ISO 8601 string, from RSS pubDate
  metadata: Record<string, unknown>;   // source-specific extras (author, categories, guid, …)
}

export interface IntelSource {
  /** Display name shown in logs, e.g. 'Splash247' */
  name: string;
  /** Source category, e.g. 'rss' */
  source_type: string;
  /**
   * How often this source should be polled (minutes).
   * The ingestion runner respects per-source schedules.
   * Default: 20 minutes.
   */
  scheduleMinutes: number;
  /**
   * Fetch new items from this source.
   * May throw — the runner catches and records errors per-source so one
   * failing feed does not block others.
   */
  fetch(): Promise<IntelItem[]>;
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const registeredSources: IntelSource[] = [];

export function registerSource(s: IntelSource): void {
  registeredSources.push(s);
}
